name: Setup Java and Checkout
description: Common Java setup

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java }}
        cache: maven

inputs:
  java:
    required: true
    description: Java version to use
