name: Setup Java and Checkout
description: Common Java setup

runs:
  using: composite
  steps:
    #- uses: actions/checkout@v3
    - run: 
        shell: bash
        echo: Setting up Java ${{ inputs.java }}


inputs:
  java:
    required: true
    description: Java version to use
