name: Setup Java and Checkout
description: Common Java setup

runs:
  using: composite
  steps:
    #- uses: actions/checkout@v3
    - run: |
        echo "Setting up Java ${{ inputs.java }}"
        echo "Distribution: temurin"
        echo "Java version: ${{ inputs.java }}"
        echo "Cache: maven"

inputs:
  java:
    required: true
    description: Java version to use
