# ------------------------------------------
# lint-template.yml
# Lints Java code using Checkstyle
# ------------------------------------------
    name: "Lint Template"

    on:
      workflow_call:
        inputs:
          java-version:
            required: true
            type: string
#        secrets:
#          SONAR_PROJECT_KEY:
#            required: true
    
    jobs:
      lint:
        name: Lint Java Code
        runs-on: ubuntu-latest
        steps:
   
          - name: Run Checkstyle
            run: ehco Running Java $ {{ input. java-version}}
    