name: "Java CI/CD Master Pipeline"

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  MAVEN_CACHE: ~/.m2/repository
#  SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}

jobs:
  # 1. Lint job
  lint:
    name: Lint Code Style
    uses: ./.github/workflows/lint-template.yml
    with:
      java-version: 17
#    secrets:
#      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
